language: python
matrix:
  include:
  - sudo: required
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
install:
- docker pull $DOCKER_IMAGE
script:
- docker run --rm -v `pwd`:/ising $DOCKER_IMAGE $PRE_CMD /ising/travisci/build-wheels.sh
- ls wheelhouse/
- echo $TWINE_PASSWORD
env:
  matrix:
    secure: ZPuvxyXIFLuY2mj6LsWlkF5snRetqVv0WHgkX92M0Q7tpPkwwcKEHD58O0zJSSc0fREVJU3rlpsL/b3np2rE8aE07jCtDbCDpYOsGgGfVvctURNRHchkvfGljMMIMuhIzmbZPSCTsiJMIrqQ6IpXj2g2CYR6sB1/ixN5Dfx5V7nKf4thnxOxdFvJt3F8H2mPsgXgfuw7SkznT/amXeQrVq3DVrtcMyLvpjWkAjGf8OBriZA6QWx5+l/7qzNa6c1EDBUh80H8pCyzqDkBJFNt4dzeZxkWMOgcyPJ8a3sqJjpooiZtSnBOLyo2QVB7ivJ8WveCqGWKHlt8ipWVZUnFgZMeqoSpMFldcF9K6urmEf/M0NDUMbbBb+ExZ9KU/ahWqZgKwYuFVO4WD33XpYdm1ZmAK6Jt6FaKjp/DgzbtHonEvziitjt5QlIy/ANzd6KmNtVuKQzllEnbv1l5NEYPECmA5NJiPs/xou2HRdGDSHKONZ6K4swpXJLZFM5C8Z5fL9rDFW5wtnz0jVX71khT+YTDDxp72JyWGWHPN+VmpmO0mc8FqlUbm9aF8gY9VnzfYz0NZ1Uf+bowSOgnADDRVKGOwL7KU7OQIkzrrZyAyQ1hyUSEYVGPM/kha/yuHZOhpJ3TxABMtuK4Vz/Zq3GTTrMg0sIaX20Ukh/vNJOM5OU=
