language: python
python:
- '2.7'
- '3.6'
- '3.7'
before_install:
  - sudo apt-get install -y gfortran
  - travis_retry wget --progress=dot:mega https://developer.nvidia.com/compute/cuda/9.2/Prod2/local_installers/cuda_9.2.148_396.37_linux
  - chmod +x cuda_*_linux
  - sudo ./cuda_*_linux --silent --toolkit
  - export CUDA_HOME=/usr/local/cuda-9.2
  - export LD_LIBRARY_PATH=${CUDA_HOME}/lib64:${LD_LIBRARY_PATH}
  - export PATH=${CUDA_HOME}/bin:${PATH}
install:
- pip install .
- pip install codecov
script:
- coverage run setup.py test
after_success:
- codecov
deploy:
  provider: pypi
  username: dexter2206
  password:
    secure: qekTicWQZ6LBty2PGWqWew+bUsXCzrvSrVpYb7CNt9PtYTjYrBPVFFcIL3jK8ebl7/8PSIzKGIMYWV3cMEkxu/8MQbDn3ApRkQzPMeb48gHcMtIO0nXrIqHKd0PAWdyQqBb7cAgSFftR5P/Ct7y0vS1gjEf00bph6gX5ZKsSABo43AiEPnZVXYObsGgqMvVIIBleQN5igSHYgtB+J2rs9sZMCdnaSZBbbqy9LEJhpzstigqgMeKJwWcnxRlMiOeQkRWnL0UMpHbjSQFnUWbumJ6yr4Ix0I9zuGsWyEshHeIkjEo1DsCstyJkT2nVwUTZE1YRHvLeSfuC6yRj+7sUD29AXs/3B9j5AAEiAgh3SjLJ/4t7E8C71GmC/FXawV5zz0jvyWx/Nh74qb7DLWTRRt+rLt1yl3VOcHho+XkwysVwIomxuklEMIcKz4Dar0+ETuFF8ZZCm5MGX6o498UvlVNjacVWSTRoVujnxL3BDTrJrEQvRGSH9lhLPMGnbxCYsnJX7aE6/1UT3TzJkQnPMsvb1giAEprkTd+uU58Kbxp7NoJxR4M88dUh9wXj4CcqMKMfWLMVWUUX/70at5TFAJ6UV0jL8UFKxKkWVQ37WHScf0tqfvqEBMoTR+hSO/NyZJc7StO7l3i4z/tqItd1Dr+iJtBed9rkRmkcOnRLgbU=
