language: python
matrix:
  include:
  - sudo: required
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
install:
- docker pull $DOCKER_IMAGE
script:
- wget https://github.com/thrust/thrust/releases/download/1.8.1/thrust-1.8.1.zip
- unzip thrust-1.8.1.zip
- docker run --rm -v `pwd`:/ising $DOCKER_IMAGE $PRE_CMD /ising/travisci/build-wheels.sh
- ls wheelhouse/
- echo $TWINE_PASSWORD
env:
  global:
  - secure: X6Rtbzhmz5hj22U+qqRMlcKkmT8wL/CDnbUoYQAVQmrP48SnJBMDNh2f3vniGDeGHMT11RqaJjThXCi48J5p+FRbOMgLFWR6oJDlBHR6UHHldFEf+v3vL3oHwc+yDEMVTUx0JEZA8JGFvN+H3AKN1MQZwHWwJUtN7yir++4KM7NnE4G9cZGPEpxaZJTQzpq6SMb5sneveK70Q2mSQZyLrQ8qLaQCY+mTuyL3frHBYadQrjX08S2QaVorQtBS0+/XcZmE8m5LKgWqM+hDSYP0Owid+vOhxpWCzRjJd99EkTJHc98dLXImCzIYBepj+2PwPUHn7il7rRs58awLYGN7/GaBDJT/b2ApZ/PEJnKRfpBdALVP2OHqhj9xjLLLPm+SVILtY/m413fCopkugbuXACiVYaTTzaxZLVrQ3wodIQIOstCmWQNxMsiSyaLnLz9vqRODciUfnl/FiwIKENYCwO/peUzw77snL3Cq29Um79k4x2KBDVHkpgB/OVsyRSXs1fnA1XPzuSjHwiRwxC+I8x08Bw4vlFBa8bNfwMWSkn/oI18g8MZL90nNNESDvCw1GKqI4JRlfVQoDjtlIErZ8ayuPHsHMXyLQszZKjzFdKf8j8Jn8saUaRcdTlaURd9X0crd7Im76NPuxl2uo7Nng7UMwBpkV8XmqT7EaOfhdqE=
deploy:
  provider: script
  skip_cleanup: true
  script: bash travisci/upload-wheels.sh
  on:
    branch: master
