language: python
matrix:
  include:
  - sudo: required
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
install:
- docker pull $DOCKER_IMAGE
script:
- wget https://github.com/thrust/thrust/releases/download/1.8.1/thrust-1.8.1.zip
- unzip thrust-1.8.1.zip
- docker run --rm -v `pwd`:/ising $DOCKER_IMAGE $PRE_CMD /ising/travisci/build-wheels.sh
- ls wheelhouse/
- echo $TWINE_PASSWORD
env:
  global:
  - secure: bFdOa78kM7vTrwNSpCrsbFJApyMxSOVHFyWSQEQ8hq6UG0CX4gtOaBXw5elaGCgcDGKEGfeggzcnq+IDnU8S+qA/483MJ4gvUKNRD/hkOJGbl0Hx3o8ewhF0nFXVr8Z2CIylamuPo681w14IPNmH4SuHwwe/dsE7VkQ9ZiBKF8GrWN5ffqxrgsTdcOo+ISn7zitEgEIyKry27KP8Z7emYbnmlkka2S8Qghk7CoXIAuaETgrFxo8VpWHGIgnYsbbrflfUucR6UNPLYxhCY4YtoPYgDZngo7jH6bwEffpsWekMVBKt8hCwM/vKkNioHHlc7iKcR4cctQ/thNc/S5Oy8N6aA78v/kUTNrHJdIeEcBZ44oVxIx27IzxPP1e7EGzIebstxB2J1haWugxChrQkWzPT41oBjDBUlKnJRyOHoI8F4hgy/xWMRovvZ4spfiOGrQttbS/2g14prmkTjkdH+XJeSE5gNnBIukK4xtLPIC3rTucYMl5s+amrHJe587Dua8x4bALtQw0s+JKllhaNewr+/C9zUfwi2ABgGkxx9siHDdwr1l2aE8sGGWtg+3mXdeQBdKCmIeXjR8xKBZSQEXkELGY5vcgsVKAFaDb0D7svY0rViDkbM0TgxDxSyz7FeHHf5cseNUzklaJrdPjCENkyyQqo4UZAnnkP5yZNjx8=
deploy:
  provider: script
  skip_cleanup: true
  script: bash travisci/upload-wheels.sh
  on:
    branch: master
